# -*- coding: utf-8 -*-
"""Shares Outstanding.ipynb

Automatically generated by Colaboratory.

#Shares Outstanding
pulls historical shares outstanding from from sharesoutstandinghistory.com based on a ticker
"""

import bs4 as bs
import urllib.request
import pickle
import requests
import os
import pandas as pd

def open_share_hist(ticker):
  #make sure ticker is lower case
  ticker = ticker.lower()
  
  #if rerunning on stock, load the pickle
  if os.path.exists('SharesOutstanding_{}.pickle'.format(ticker)):
    with open('SharesOutstanding_{}.pickle'.format(ticker), "rb") as f:
            sh_os = pickle.load(f)
  
  #if first run on stock, scrape it, then save the pickle
  if not os.path.exists('SharesOutstanding_{}.pickle'.format(ticker)):
    resp = requests.get('https://www.sharesoutstandinghistory.com/{}/'.format(ticker))
    soup = bs.BeautifulSoup(resp.text, 'lxml')
    table = soup.find('table', {'class': 'infotable'})

    sh_os = pd.DataFrame(data=[],columns=["Date","SharesOut"])
    for row in table.findAll('tr')[3:]:
        sh_date = row.findAll('td')[0].text
        sh_out = row.findAll('td')[1].text
        sh_os = sh_os.append({'Date': sh_date, 'SharesOut': sh_out}, ignore_index=True)
       
    with open('SharesOutstanding_{}.pickle'.format(ticker),"wb") as f:
        pickle.dump(sh_os,f)
        
return(sh_os)
